name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print read
        run: echo "Hello world!"
      - name: print goodbye
        run: echo "bye"
